#!/bin/bash
# File: commit-msg
# Author: Anicka Burova <anicka.burova@gmail.com>
# Date: 08.07.2017
# Last Modified Date: 13.07.2017
# Last Modified By: Anicka Burova <anicka.burova@gmail.com>
#!/bin/bash
# commit-msg
# Copyright (c) 2017 Anicka Burova <anicka.burova@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ -f .versionrc ]
then
    source .versionrc
fi

has_msg=$(versioner-has-msg.py < $1 && echo msg)

if [ "$has_msg" == "msg" ]
then
    version=$(versioner.py $MAIN_VERSION_FILE -s -v)
    orig_msg=$(<$1)
    echo "$version: $orig_msg" > $1
fi
