#!/bin/bash
# File: post-commit
# Author: Anicka Burova <anicka.burova@gmail.com>
# Date: 13.07.2017
# Last Modified Date: 13.07.2017
# Last Modified By: Anicka Burova <anicka.burova@gmail.com>

if [ -f ".version_upgrade" ]
then
    source ".version_upgrade"
    git --no-pager log | grep $OLD_VERSION
fi

