#!/bin/bash

if [ -f .versionrc ]
then
    source .versionrc
fi

files=$(git diff --name-only --cached)

main=false

for file in $files
do
    if [ "$MAIN_VERSION_FILE" = "$file" ]
    then
        main=true
    fi
    # test if it is upgradable file
    versioner.py $file -s --maintenance 2>/dev/null 1>/dev/null
    res=$?
    if [ "$res" == "0" ]
    then
        # now try to upgrade
        text=$(versioner.py $file -s --maintenance)
        versioner-update $file --maintenance
        git add $file
        echo "$file: $text"
    fi
done

if [ "$main" = false ]
then
    if [ -f $MAIN_VERSION_FILE ]
    then
        versioner-update $MAIN_VERSION_FILE --maintenance
        git add $MAIN_VERSION_FILE
        echo "The main \"$MAIN_VERSION_FILE\" has been updated"
    fi
fi

