#!/bin/bash
# File: pre-commit
# Author: Anicka Burova <anicka.burova@gmail.com>
# Date: 08.07.2017
# Last Modified Date: 08.07.2017
# Last Modified By: Anicka Burova <anicka.burova@gmail.com>
# pre-commit
# Copyright (c) 2017 Anicka Burova <anicka.burova@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ -f .versionrc ]
then
    source .versionrc
fi

# exit if the versioning mode is not auto
if [ "$VERSION_MODE" != "auto" ]
then
    exit 0
fi

files=$(git diff --name-only --cached)

main=false

for file in $files
do
    if [ "$MAIN_VERSION_FILE" = "$file" ]
    then
        main=true
    fi
    # test if it is upgradable file
    versioner.py $file -s --maintenance 2>/dev/null 1>/dev/null
    res=$?
    if [ "$res" == "0" ]
    then
        # now try to upgrade
        text=$(versioner.py $file -s --maintenance)
        versioner-update $file --maintenance
        git add $file
        echo "$file: $text"
    fi
done

if [ "$main" = false ]
then
    if [ -f $MAIN_VERSION_FILE ]
    then
        versioner-update $MAIN_VERSION_FILE --maintenance
        git add $MAIN_VERSION_FILE
        echo "The main \"$MAIN_VERSION_FILE\" has been updated"
    fi
fi

