#!/bin/bash

# these are the sha1 of hook files installed by the versioner
pre_commit_sha=9d0ead3b6baabf15425a9d405d75730d38030b96
commit_msg_sha=51539eeb262799f637d81d334bf952d47bb5d3a0

current_pre_commit_sha=$(sha1sum .git/hooks/pre-commit | awk '{print $1;}')
current_commit_msg_sha=$(sha1sum .git/hooks/commit-msg | awk '{print $1;}')

if [ "$pre_commit_sha" == "$current_pre_commit_sha" ]
then
    echo deleting pre-commit
    rm -f .git/hooks/pre-commit
fi

if [ "$commit_msg_sha" == "$current_commit_msg_sha" ]
then
    echo deleting commit-msg
    rm -f .git/hooks/commit-msg
fi
