#!/bin/bash
# File: versioner-update
# Author: Anicka Burova <anicka.burova@gmail.com>
# Date: 07.07.2017
# Last Modified Date: 14.07.2017
# Last Modified By: Anicka Burova <anicka.burova@gmail.com>

if [ -f ".versionrc" ]
then
    source .versionrc
else
    echo "no .versionrc"
    exit 1
fi

lang=""
if [ "$VERSION_LANG" != "" ]
then
    lang="-l $VERSION_LANG"
fi

if [ $# -eq 0 ]
then
    versioner.py $MAIN_VERSION_FILE $lang --show
    exit 0
fi

if [[ "$1" == "--major" || "$1" == "--minor" || "$1" == "--main" || "$1" == "--build" ]]
then
    tmpfile=$(mktemp /tmp/versioner.XXXXXX)

    if [ -f $MAIN_VERSION_FILE ]
    then
        versioner.py $MAIN_VERSION_FILE $lang $* > $tmpfile && mv $tmpfile $MAIN_VERSION_FILE
    fi
    rm -f $tmpfile
fi
