#!/bin/bash

if [ "$1" == "uninstall" ]
then
    echo "uninstalling versioner files, manually remove pre-commit from affected git repositories"
    rm /usr/local/bin/versioner-install
    rm /usr/local/bin/versioner-pre-commit
    rm /usr/local/bin/versioner.py
    rm /usr/local/bin/versioner-update
    exit 0
fi

if [ "$0" == "./install_versioner" ]
then
    echo "running app install"

    install versioner-install /usr/local/bin
    install pre-commit /usr/local/bin/versioner-pre-commit
    install versioner.py /usr/local/bin
    install versioner-update /usr/local/bin
    exit 0
fi

versioner_dir="$(dirname $0)"
echo $versioner_dir
exit 0


if [ ! -d .git ]
then
    echo "cannot find .git folder, is this a git repository? exiting..."
    exit 1
fi

echo "What is the main version file: "
read main_file
if [ ! -f $main_file ]
then
    echo "cannot find $main_file, exiting..."
    exit 2
fi

echo "MAIN_VERSION_FILE=$main_file" > .versionrc

versioner_dir="$(dirname $0)"

ln -sf $versioner_dir/versioner.py versioner.py
ln -sf $versioner_dir/version_update version_update

ln -sf $versioner_dir/pre-commit .git/hooks/pre-commit

echo Done

