#!/bin/bash
# File: versioner-update
# Author: Anicka Burova <anicka.burova@gmail.com>
# Date: 07.07.2017
# Last Modified Date: 08.07.2017
# Last Modified By: Anicka Burova <anicka.burova@gmail.com>
#!/bin/bash

if [ -f ".versionrc" ]
then
    source .versionrc
else
    echo "no .versionrc"
    exit 1
fi

if [ $# -eq 0 ]
then
    versioner.py $MAIN_VERSION_FILE --show
    exit 0
fi

tmpfile=$(mktemp /tmp/versioner.XXXXXX)

if [ -f $MAIN_VERSION_FILE ]
then
    versioner.py $MAIN_VERSION_FILE $* > $tmpfile && mv $tmpfile $MAIN_VERSION_FILE
fi
rm -f $tmpfile


