#!/bin/bash

if [ "$1" == "uninstall" ]
then
    echo "uninstalling versioner files, manually remove pre-commit from affected git repositories"
    rm -v /usr/local/bin/versioner-install
    rm -v /usr/local/bin/versioner-pre-commit
    rm -v /usr/local/bin/versioner.py
    rm -v /usr/local/bin/versioner-update
    exit 0
fi

if [ "$0" == "./versioner-install" ]
then
    echo "running app install..."

    install -v versioner-install /usr/local/bin
    install -v pre-commit /usr/local/bin/versioner-pre-commit
    install -v versioner.py /usr/local/bin
    install -v versioner-update /usr/local/bin

    echo "installed"
    exit 0
fi


if [ ! -d .git ]
then
    echo "cannot find .git folder, is this a git repository? exiting..."
    exit 1
fi

echo "What is the main version file: "
read main_file
if [ ! -f $main_file ]
then
    echo "cannot find $main_file, exiting..."
    exit 2
fi

echo "MAIN_VERSION_FILE=$main_file" > .versionrc

versioner_dir="$(dirname $0)"

#ln -sf $versioner_dir/versioner.py versioner.py
#ln -sf $versioner_dir/version_update version_update

ln -sf $versioner_dir/versioner-pre-commit .git/hooks/pre-commit
echo ".versionrc" >> .gitignore

echo Done

