#!/bin/bash
# File: uninstall-hooks
# Author: Anicka Burova <anicka.burova@gmail.com>
# Date: 07.07.2017
# Last Modified Date: 07.07.2017
# Last Modified By: Anicka Burova <anicka.burova@gmail.com>
# uninstall-hooks
# Copyright (c) 2017 Anicka Burova <anicka.burova@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# File: uninstall-hooks
# Author: Anicka Burova <anicka.burova@gmail.com>
# Date: 07.07.2017
# Last Modified Date: 07.07.2017
# Last Modified By: Anicka Burova <anicka.burova@gmail.com>



# these are the sha1 of hook files installed by the versioner
pre_commit_sha=9d0ead3b6baabf15425a9d405d75730d38030b96
commit_msg_sha=51539eeb262799f637d81d334bf952d47bb5d3a0

current_pre_commit_sha=$(sha1sum .git/hooks/pre-commit | awk '{print $1;}')
current_commit_msg_sha=$(sha1sum .git/hooks/commit-msg | awk '{print $1;}')

if [ "$pre_commit_sha" == "$current_pre_commit_sha" ]
then
    echo deleting pre-commit
    rm -f .git/hooks/pre-commit
fi

if [ "$commit_msg_sha" == "$current_commit_msg_sha" ]
then
    echo deleting commit-msg
    rm -f .git/hooks/commit-msg
fi
